# -*- coding: utf-8 -*-
"""Librerias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSys7ZSSAB_4p3ir_G3r9QI3h5givd-7
"""

import numpy as np
import csv
import json

lista = np.array([2,3,4,5,100,-10])
# print(lista, type(lista))

# print(lista + 5)  # suma 5 a todos los elementos de la lista
# print(lista * 5)  # multiplica 5 a todos los elementos de la lista

print(lista.max())

print(lista.min())
print(lista.mean())
print(lista.std())
print(lista.sum())
print(np.median(lista))
print(np.min(lista))

print(lista[0])

from numpy import random as rd

lista =[6 ,7 ,8 ,9 ,10 ,11 ,12]
rd.shuffle(lista)
print(lista)

import numpy as np

lista =[6 ,7 ,8 ,9 ,10 ,11 ,12]
np.random.shuffle(lista)
print(lista)

#lista =[0,0,0,0,0,0,0,0]
lista = np.ones(10,dtype=int)
print(lista)

import pandas as pd
diccionario_pais ={
    "pais"    : ["Brazil", "Russia", "Colombia", "China","panama"],
    "capital" : ["Brasilia", "Moscow", "Bogota", "Pekin","ciudad panama"],
}
info_paises = pd.DataFrame(diccionario_pais, columns=["pais","capital"])
print(info_paises)

import pandas as pd

diccionario_pais ={
    "pais"    : ["Brazil", "Russia", "Colombia", "China","panama"],
    "capital" : ["Brasilia", "Moscow", "Bogota", "Pekin","ciudad panama"],
}

diccionario_area ={
    "pais"    : ["Brazil", "Russia", "Colombia", "China","España"],
    "area"    : [8654, 10520, 2225, 9750,1234],
}

#print(diccionario)
info_paises = pd.DataFrame(diccionario_pais, columns=["pais","capital"])
info_paises_area = pd.DataFrame(diccionario_area, columns=["pais","area"])

info_paises_new = info_paises.merge(info_paises_area, how="right", on=["pais"])


#print(info_paises, type(info_paises))

#print(info_paises["pais"])

print(info_paises)
print(info_paises_area)
print(info_paises_new)

lista = [2,3,4,5]
print(lista + 5)

import numpy as np

lista = np.arange(1,11,2,dtype=float)
print(lista)

nombre = input()